In [5]:
import cv2
import sys, os
import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import imageio
import numpy as np
from numpy import asarray

# DeepFake Detection Algorithm
Input : $D_{real}$, $D_{fake}$ were centered by subtracting the mean of the real training data.

## Create $D_{real}$

In [8]:
# Read images
img_real = []
path = '/content/drive/MyDrive/American_University/2021_Fall/DATA-793-001_Data Science Practicum/Datasets/manipulated_sequences/Deepfakes/raw/videos/data_test'

for root, _, files in os.walk(path):
    current_directory_path = os.path.abspath(root)
    for f in files:
        name, ext = os.path.splitext(f)
        if ext == ".jpg":
            current_image_path = os.path.join(current_directory_path, f)
            current_image = imageio.imread(current_image_path)
            img_real.append(current_image)
img_real = np.array(img_real, dtype=object)
for img in img_real:
  print(img.shape)
print(len(img_real))
print(img_real[0])

(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(480, 854, 3)
(480, 854, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
10
[[[ 50  30  93]
  [ 42  54 152]
  [ 24  71 213]
  ...
  [ 10  55 219]
  [ 10  40 172]
  [  4  21 125]]

 [[ 48  27  92]
  [ 43  52 153]
  [ 23  69 214]
  ...
  [ 12  56 223]
  [ 12  42 176]
  [  7  24 130]]

 [[ 48  25  93]
  [ 42  51 154]
  [ 23  69 216]
  ...
  [ 17  59 229]
  [ 15  44 182]
  [ 10  27 135]]

 ...

 [[  2   2   2]
  [  2   2   2]
  [  2   2   2]
  ...
  [  0   0   8]
  [  0   0   8]
  [  0   0   8]]

 [[  2   2   2]
  [  2   2   2]
  [  2   2   2]
  ...
  [  0   0   8]
  [  0   0   8]
  [  0   0   8]]

 [[  2   2   2]
  [  2   2   2]
  [  2   2   2]
  ...
  [  0   0   8]
  [  0   0   8]
  [  0   0   8]]]


## Global Centering for each image

In [9]:
def meanSubtraction(arr):
  new_arr = []
  for i in range(len(arr)):
    img = arr[i]
    img = img.astype(np.float32) # convert from integers to floats
    mean = img.mean() # calculate global mean
    img = img - mean # centering of pixels
    img /= img.std()
    new_arr.append(img)
  new_arr = np.array(new_arr, dtype=object)
  return new_arr

img_real = meanSubtraction(img_real)
print(len(img_real))
print(img_real[0])

10
[[[-0.43175367 -0.65193266  0.0416312 ]
  [-0.5198253  -0.38771784  0.69115925]
  [-0.71798635 -0.2005657   1.3627052 ]
  ...
  [-0.8721117  -0.3767089   1.428759  ]
  [-0.8721117  -0.5418432   0.91133827]
  [-0.93816537 -0.7510132   0.39391762]]

 [[-0.45377156 -0.68495953  0.03062226]
  [-0.5088163  -0.40973577  0.7021682 ]
  [-0.7289953  -0.2225836   1.3737142 ]
  ...
  [-0.8500938  -0.36569995  1.4727948 ]
  [-0.8500938  -0.5198253   0.95537406]
  [-0.9051385  -0.71798635  0.44896236]]

 [[-0.45377156 -0.7069774   0.0416312 ]
  [-0.5198253  -0.42074472  0.71317714]
  [-0.7289953  -0.2225836   1.395732  ]
  ...
  [-0.795049   -0.3326731   1.5388485 ]
  [-0.8170669  -0.49780735  1.0214278 ]
  [-0.8721117  -0.68495953  0.5040071 ]]

 ...

 [[-0.96018326 -0.96018326 -0.96018326]
  [-0.96018326 -0.96018326 -0.96018326]
  [-0.96018326 -0.96018326 -0.96018326]
  ...
  [-0.98220116 -0.98220116 -0.8941296 ]
  [-0.98220116 -0.98220116 -0.8941296 ]
  [-0.98220116 -0.98220116 -0.8941296 ]]


# Preprocessing and data tensor organization

In [ ]:
print(img_real.shape)
[U_real, S_real, V_real] = np.linalg.svd(img_real[0])

(10,)


In [ ]:
for i in range(len(img_real)):
  [U_real, S_real, V_real] = np.linalg.svd(img_real[i])
  

(720, 3, 3)


# Testing Zone

In [ ]:
"""
img_df = []           
for img in images:
  img = img.flatten()
  img_df.append(img)
  print(img.shape)
img_df = np.array(img_df, dtype=object)
print(img_df)
"""